from collections.abc import Sequence
from typing import Any, Protocol
from uuid import UUID

from cuekb.domain.models import Chunk, Document, DocumentVersion, Job, KnowledgeBase


class Repository(Protocol):
    def create_knowledge_base(self, kb: KnowledgeBase) -> KnowledgeBase: ...
    def get_knowledge_base(self, kb_id: UUID) -> KnowledgeBase | None: ...
    def create_document(self, document: Document, version: DocumentVersion, job: Job) -> None: ...
    def get_job(self, job_id: UUID) -> Job | None: ...
    def publish_chunks(self, job_id: UUID, chunks: Sequence[Chunk]) -> Job: ...
    def context_chunks(self, chunk: Chunk, limit: int) -> list[Chunk]: ...
    def related_chunks(
        self, request: Any, seed_ids: Sequence[UUID], limit: int, timeout_ms: int
    ) -> list[dict]: ...
    def visible_chunks(self, kb_ids: Sequence[UUID]) -> list[Chunk]: ...
    def load_chunks(self, ids: Sequence[UUID], kb_ids: Sequence[UUID]) -> list[Chunk]: ...


class SearchBackend(Protocol):
    def index(
        self, chunks: Sequence[Chunk], vectors: Sequence[Sequence[float]] | None = None
    ) -> None: ...
    def keyword_search(
        self, query: str, kb_ids: Sequence[UUID], filters: dict[str, Any], limit: int
    ) -> list[tuple[UUID, float]]: ...
    def vector_search(
        self, vector: Sequence[float], kb_ids: Sequence[UUID], filters: dict[str, Any], limit: int
    ) -> list[tuple[UUID, float]]: ...
    def delete_document(self, document_id: UUID) -> None: ...


class ModelClient(Protocol):
    @property
    def embedding_model(self) -> str: ...
    def embed(self, texts: Sequence[str], timeout_ms: int) -> list[list[float]]: ...
    def rerank(self, query: str, passages: Sequence[str], timeout_ms: int) -> list[float]: ...
