from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from cuekb.domain.models import Chunk, Document, DocumentVersion, Job, KnowledgeBase


class Repository(Protocol):
    def create_knowledge_base(self, kb: KnowledgeBase) -> KnowledgeBase: ...
    def get_knowledge_base(self, kb_id: UUID) -> KnowledgeBase | None: ...
    def create_document(self, document: Document, version: DocumentVersion, job: Job) -> None: ...
    def get_job(self, job_id: UUID) -> Job | None: ...
    def publish_chunks(self, job_id: UUID, chunks: Sequence[Chunk]) -> Job: ...
    def visible_chunks(self, kb_ids: Sequence[UUID]) -> list[Chunk]: ...


class SearchBackend(Protocol):
    def index(self, chunks: Sequence[Chunk]) -> None: ...
    def keyword_search(self, query: str, chunks: Sequence[Chunk], limit: int) -> list[tuple[Chunk, float]]: ...
    def vector_search(self, query: str, chunks: Sequence[Chunk], limit: int) -> list[tuple[Chunk, float]]: ...
